### PR TITLE
Some template change requests

### PR DESCRIPTION
**Pull request by vb000**
I implement following changes... let me know if this looks okay.

- I think we should use `if __name__ == "__main__"` construct to be able to reuse the class we defined in the script in some other script. It's good to have that flexibility, and from what I understand, it's considered a good python practice to not run from the start of the script.
- I think clearly separating out model and hyper-parameters improves readability and makes the model easy to comprehend. I followed this approach of naming hyper-parameters in block letters:
https://github.com/cornell-brg/pytorch-apps/blob/8315c847ea714d7d8783c15f4297bc038e992aaf/template/template.py#L81-L85
As of now, these are things that define the model and training, so better to bunch them together?
- Hyper-parameters should be added as extra command line arguments by each workload. I agree we shouldn't move from defaults, but it might not hurt to have the flexibility. At least they show up in the help message for the user to understand what hyper-parameters are available.
https://github.com/cornell-brg/pytorch-apps/blob/8315c847ea714d7d8783c15f4297bc038e992aaf/template/template.py#L41-L51

### CODE REVIEW

**Comment by yodada** [comment]
Emmm regarding __name__ == ‘__main__’, I think the argument here is this file wont be imported by any other files

**Comment by vb000** [comment]
Won't be imported or shouldn't be imported? If it shouldn't be imported ever, we shouldn't have __name__ == "__main__". 

If won't be imported as of now, why not have the flexibility? It doesn't hurt. May be workloads can share class but train with different hyper-parameters!

**Comment by vb000** [comment]
General python script structure I've seen is accepted is:

```
# imports #

# classes, functions and other definitions #

if __name__ == "__main__":
    # runnable script #
```

**Comment by sampsyo** [comment]
FWIW, I generally tend to agree that a `__main__` check is nice to have in case unforeseen circumstances create a reason to import the module in a future.

I'd even go one step further and recommend that most code go inside a function. It's not just cosmetic—code inside functions is faster (because it uses local variables instead of globals) and less error prone (because the variables are limited in scope instead of instantly contaminating all functions in the module).

**Comment by yodada** [comment]
Ok! Sounds good!

**Pull request merged**
